
debug: true

server:
  port: 9004
spring:
  application:
    name: IgniteMybatis

#  ignite:
#    datasource:
#      url: jdbc:ignite:thin://127.0.0.1/
#      driver-class-name: org.apache.ignite.IgniteJdbcThinDriver
#      type: com.zaxxer.hikari.HikariDataSource
#      initialSize: 20
#      minIdle: 20
#      maxActive: 20
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      validationQuery: SELECT 1
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      filters: stat

#  datasource:
#    url: jdbc:ignite:thin://127.0.0.1:10800/
#    driver-class-name: org.apache.ignite.IgniteJdbcThinDriver


  datasource:
    url: jdbc:ignite:cfg://config/ignite-jdbc.xml
    driver-class-name: org.apache.ignite.IgniteJdbcDriver
    ignite:
      jdbc:
        transactionsAllowed: true
    hikari:
      connection-timeout: 60000                  # Default: 30000 (30 seconds)
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 50                           # Default: same as maximumPoolSize
      maximum-pool-size: 500                     # Default: 10


#    type: com.zaxxer.hikari.HikariDataSource
#    initialSize: 20
#    minIdle: 20
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    validationQuery: SELECT 1
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    filters: stat

#    init: true
#    schema: classpath:db/schema.sql
#    data: classpath:db/data.sql

ignite-client:
  addresses: 127.0.0.1:10800 # this is mandatory property!
  timeout: 10000
  tcpNoDelay: false

mybatis:
  type-aliases-package: org.rgs.mapper
  mapper-locations: classpath:mappers/*.xml



#logging:
#  level:
#    #web: DEBUG
#    org.springframework.security.web: DEBUG
